# Change these first
owner: DineUpGroup # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: DineUp
    url: https://app.dineup.com/api/ping
  - name: Test
    url: https://test.dineup.com/api/ping
  - name: Staging
    url: https://staging.dineup.com/api/ping
  - name: Development
    url: https://development.dineup.com/api/ping
  - name: Website
    url: https://dineup.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dineup.com
  # baseUrl: /your-repo-name
  logoUrl: https://dineup.com/hubfs/24084423/logo-color-white.png
  name: Status
#   introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#   introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Hubspot
      href: https://status.hubspot.com/
    - title: Slack
      href: https://status.slack.com/
    - title: GitHub
      href: https://www.githubstatus.com/
    - title: Digital Ocean
      href: https://status.digitalocean.com/
    - title: Cloudflare
      href: https://www.cloudflarestatus.com/
      
  customHeadHtml: "<style>body { font-size: 14px !important; } .container:nth-of-type(1) { max-width: 100%; } .live-status { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); grid-gap: 10px; }</style>"
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
